User Epoch PNL
rysk-finance/dynamic-hedging pull request #290
Opened 2022-10-24 11:37 UTC by devey

# Task:

Add historical PNL for user under Dashboard. 

## Description

Use historical `PricePerShare` (per epoch), users' withdraws (in shares) and deposits (in `USDC` collateral) to calculate PNL over epoch and plot it.
 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update
- [ ] Quality of life improvement

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have NATSPEC'd any new functions
- [ ] If appropriate, I have properly tested my new functionality

2023-01-23 16:24 UTC, devey commented
@MeanBoyCousin any idea why deploy on Vercel fails? I rebased on `rysk-alpha`

2023-01-24 09:48 UTC, MeanBoyCousin commented
> @MeanBoyCousin any idea why deploy on Vercel fails? I rebased on `rysk-alpha`

From the build logs, it looks like linting errors.

https://vercel.com/rysk-finance/rysk-alpha/4JqQniJhP9bc9rLMJA3E5xxJdoug#L32

2023-01-24 13:04 UTC, devey commented
> > @MeanBoyCousin any idea why deploy on Vercel fails? I rebased on `rysk-alpha`
> 
> From the build logs, it looks like linting errors.
> 
> https://vercel.com/rysk-finance/rysk-alpha/4JqQniJhP9bc9rLMJA3E5xxJdoug#L32

thanks, fixed

2023-01-26 22:29 UTC, ugolino commented
@devey this looks good to merge IMO

2023-01-26 22:29 UTC, ugolino approved these changes

2023-01-27 11:25 UTC, devey commented
@ugolino I made some fixes from @kjr217 feedback, good for me now but need to solve conflicts

2023-01-27 11:26 UTC, MeanBoyCousin requested changes
I'm not super keen on the proliferation of massive React files in this code base. I appreciate that in a more traditional setup, a lot of the computational stuff would be done on a server and abstracted away from the front end, but I think that if this is the way it has to be, we need to try and compartmentalise components in a better fashion.

I'm still getting familiar with the graph but I'd like to know if there are ways to better abstract some of the logic into there. At the moment, I am seeing the graph as the model layer in a typical MVC setup and with this, I'd typically move as much of the computational methods (data-related working) onto model methods. Can custom methods be added to the graph or do we need a middle layer to act as a view? Perhaps this would be better with NextJS as we could use the API views to query the graph and do the complex logical updates and then simply query that from the front end and only have the data we require for the components. Interested to hear your thoughts.

As far as compartmentalising goes, it'd be great to see things like:
- types/interfaces extracted to their own file or into a higher level of the repo to be more reusable.
- GraphQL queries and logic moved into their own hook-style file, removing logic from the actual JSX.
- Util functions extracted out for re-usability.

Happy to discuss all of this! 😄

2023-01-27 11:26 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +  );
There are a lot of checks to `data?.` inside here. Would be cleaner to wrap everything in an if statement and remove the need for extra checks.

2023-01-27 11:26 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +                        // TODO access color throw Tailwind helpers
I looked into this. It doesn't seem do-able with the way the repo is structured as CRA won't reference files outside of the `src` folder. Something for the future with a better framework. 👍

2023-01-27 11:26 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +                          ).toFixed(2)
We should think about removing the use of `toFixed` in favour of numeric rounding as it can cause floating point errors. Not a big deal for now but worth considering going forward.

2023-01-27 11:26 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +                          });
Recommend using dayjs here. More extensible and readable.

2023-01-27 11:26 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useUserPosition.ts
> +          .mul(latestEpochSharePrice) // withdrawal epoch share price for receipt epoch - 1
Nice docs updates, thanks!

2023-01-27 12:17 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          />
nice, I looked into this but what's the difference compared to this one?

2023-01-27 15:47 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          />
The `NumberFormat` component will automatically return a `span` tag so we end up with a `span` inside a `p` tag. It's not a big deal as it is semantically valid, but best to avoid unnecessary nesting if we can. Using the prop mentioned means we can just have the `p` tag. 👍

2023-01-30 11:26 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          />
got it

2023-01-30 11:34 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +};
Yep, I think we only have two charts for now.
Should find some more stable library as I've had various annoying issues while using Recharts.
That's probably a good time to create more reusable parts but these first charts are MVPs.

2023-01-30 11:37 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +};
I have always used [chartjs](https://react-chartjs-2.js.org/) in the past with little problems so this might be worth a try. We need to look at the branding as well because the charts on there look nothing like the charts we have now.

2023-01-30 11:49 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          dx={value > 0 ? -50 : 50}
This is the value coming from `dataKey` which in this case is:
```js
	dataKey={({ change }) =>
            parseFloat(utils.formatUnits(change, DECIMALS.USDC))
 	}
```

2023-01-30 11:50 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          fill={value > 0 ? "green" : "red"}
Should also be a `Number`.

2023-01-30 11:51 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          fontSize={13}
14 works 🙂

2023-01-30 11:54 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +          dx={value > 0 ? -50 : 50}
So in that case, should the early return above be `value === 0` or just `!value`?

2023-01-30 12:05 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +  useQuery(
We would probably need to generate types from The Graph's schema (https://www.apollographql.com/docs/react/development-testing/static-typing/) to fix this here and in all other `useQuery`

2023-01-30 12:07 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +  useQuery(
Possibly a time saver, but not a blocker to doing it manually? I did it with [this query.](https://github.com/rysk-finance/dynamic-hedging/blob/rysk-alpha/packages/front-end/src/components/VaultPerformance/VaultPerformance.tsx#L20)

2023-01-30 12:30 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +              });
i needed to read previous shares so made more sense to just have an array where i push epochs as i go and use map only to iterate over all epochs

2023-01-30 12:37 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +              });
Understandable, but I'd recommend avoiding mutation wherever possible. Mutation generally leads to harder-to-debug and harder-to-follow code.

2023-01-30 12:44 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +              });
I don't think I'm mutating anything here as the graph variable in untouched, there is a new Array with this interface of data that is computed from graph data:
```ts
interface PNL {
  epoch: string;
  pnl: string;
  change: string;
  shares: string;
  timestamp: string;
  dateLocale: string;
}
```

2023-01-30 12:58 UTC, devey commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +                          ).toFixed(2)
got it, should we just multiply and divide instead? but agree that we should write down a small doc on how to do operations on front-end

2023-01-30 13:07 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +              });
You are mutating `tempPNL` with each push. The map is constructing the list in memory and then you are pushing results from inside the map to another memory allocation and mutating it each time. Not only will just retuning improve readability but it'll also improve memory allocation. Win-win! :)

2023-01-30 13:09 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserEpochPNL.tsx
> +                        // TODO access color throw Tailwind helpers
Yeah, that is what I looked into. Annoyingly, one of the caveats with create-react-app is that it won't let you reference any files that live outside the `src` folder. This means we can't use the `resolveConfig` for any of the code inside `src` without moving the Tailwind config. I also looked into this, but the big brains at Tailwind have decided that being able to specify where your config file lives aren't required. 🤷

2023-02-03 12:55 UTC, MeanBoyCousin commented on packages/front-end/src/components/dashboard/UserVault.tsx
> +  const [unredeemableCollateral] = useState<BigNumber>(BigNumber.from(0));
Do you think we will ever need the setter here?

2023-02-03 12:56 UTC, MeanBoyCousin approved these changes
LGTM. Just have one question.

2023-02-04 17:15 UTC, devey commented on packages/front-end/src/components/dashboard/UserVault.tsx
> +  const [unredeemableCollateral] = useState<BigNumber>(BigNumber.from(0));
no, these are not necessary here as they are already being shown in `PositionTooltip` (which you access using the info button next to _Your Position_). For information, unredeemable collateral is collateral that is waiting to be deposited in the next epoch.

2023-02-04 17:24 UTC, devey commented on packages/front-end/src/components/dashboard/UserVault.tsx
> +  const [unredeemableCollateral] = useState<BigNumber>(BigNumber.from(0));
also just checked and seems like these tooltips are broken in `rysk-alpha`, going to open an issue

2023-02-04 17:27 UTC, devey commented
> LGTM. Just have one question.

nice, feel free to merge it when you can

2023-02-06 12:37 UTC, ugolino commented
LGTM. merging it

2023-02-06 12:37 UTC, merged