Feature/options trading
rysk-finance/dynamic-hedging pull request #327
Opened 2023-01-10 10:25 UTC by devey

# Task:

## Description

Implementation of trading interface using `BeyondPricer.sol` and `OptionExchange.sol`.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update
- [ ] Quality of life improvement

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have NATSPEC'd any new functions
- [ ] If appropriate, I have properly tested my new functionality

2023-02-02 11:50 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +        );
Should just use a set here if you're just checking for uniqueness.

2023-02-02 12:13 UTC, MeanBoyCousin reviewed
All looks good. Haven't gone in to too much detail as I know this is WIP. One thing that would be good though is updating the `copyABIsToFrontend` script, found at `packages\contracts\copyABIsToFrontend.sh` to include the new ABIs that you have added.

2023-02-02 12:13 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  const [optionHandlerContract] = useContract({
Question more than a comment. If this is only for fetching data and not being called, does this mean it's read-only? Just wondering what the `readOnly` key means.

2023-02-02 12:13 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +          { gasLimit: 2500000 }
Is this arbitrary or was there a calculation here to determine the limit?

2023-02-02 12:13 UTC, MeanBoyCousin commented on packages/front-end/src/state/types.ts
> +  };
These types should be interfaces, but no biggie for now!

2023-02-02 12:13 UTC, MeanBoyCousin commented on packages/front-end/src/utils/helpers.ts
> +  //   });
It doesn't look like this function is even being used anywhere. 🤔

2023-02-02 14:55 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +          { gasLimit: 2500000 }
yeah, so this one is a tx that is calling many contracts and doing lots of state updates. Usually you don't need this cause an estimate is given to MetaMask (i'm guessing by ethers: https://docs.ethers.org/v5/api/providers/provider/#Provider-getGasPrice) but in this case it's not able to estimate the gas needed so I just took it from the same input data transaction: https://dashboard.tenderly.co/tx/arbitrum-goerli/0xe4548db1002fb83836b355280502ae728f5bba1f74e41e06c0cf4139cd97b884/gas-usage (you can see it on the bottom here).

2023-02-02 14:58 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  const [optionHandlerContract] = useContract({
actually I removed this because we are not using it. In case you are just reading from a smart contracts you only need an RPC provider and no signer (so you can retrieve data without asking user to connect) but in case you will need user to sign a transaction you need a signer.

2023-02-02 15:28 UTC, devey commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +              // TODO make sure this UTC set is done in the right place
no need for this so i removed it cause it's the same as value above `unixDateWithoutMilliseconds` where values is already _8 AM UTC_ (this is the standard options expiration date).

2023-02-02 15:28 UTC, devey commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +              isPut: false, // TODO: Change this to true after figuring out why contracts reverts
just checked and it got fixed with new contract deployments! 👍🏼

2023-02-02 15:41 UTC, devey commented on packages/front-end/src/utils/helpers.ts
> +  //   });
removed it, i don't think we'll need this but in case we know where to find it 🙂

2023-02-02 15:59 UTC, devey commented
Closes #362

2023-02-02 16:00 UTC, devey commented
Closes #326

2023-02-02 16:10 UTC, devey commented
closes #348

2023-02-03 10:26 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +        );
Are you sure you pushed everything? There isn't any change here based on the comments.

2023-02-03 10:29 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +          { gasLimit: 2500000 }
Great, thank you. It'd be good to get an overview of Tenderly when you have some time. 👍

2023-02-03 10:34 UTC, MeanBoyCousin requested changes
Great work and thanks for the helpful feedback on my questions. I would appreciate an overview of Tenderly at some point as well when we can make time.

Just one small optimisation and then I think we're good to go. 👍

2023-02-03 12:14 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +        );
ahh yes, sorry I forgot that the native Set is rubbish 🤣 Used to using immutable sets from ImmutableJS which are capable of uniqueness in dicts. All good. 👍

2023-02-03 12:14 UTC, MeanBoyCousin approved these changes

2023-02-03 12:15 UTC, devey commented
> Great work and thanks for the helpful feedback on my questions. I would appreciate an overview of Tenderly at some point as well when we can make time.
> 
> Just one small optimisation and then I think we're good to go. 👍

sounds good, my knowledge of Tenderly is also not too deep but happy to do a walkthrough of a sample transaction (quite useful for debugging why front-end interactions are failing)

2023-02-04 19:29 UTC, devey commented
@MeanBoyCousin rebase here too

2023-02-06 13:03 UTC, merged