Tendenrly Operate Simulation
rysk-finance/dynamic-hedging pull request #390
Opened 2023-02-07 10:42 UTC by devey

A hook with the api call to simulate a call to `operate` method on `OptionExchange` by passing in raw input data.

Don't want to overcomplicate it for now by supporting other contracts but as other complicated methods come up we'll add them here.

Currently using it before asking user to sign transaction by showing error if simulation doesn't go through.

2023-02-08 10:46 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +            optionExchangeContract?.operate(txData, { gasLimit: 2500000 });
So do we not actually surface the simulation to the user? Maybe I misunderstood but I thought we wanted to show the user the simulation so they get an idea of the fees.

2023-02-08 10:55 UTC, kjr217 commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +        `https://api.tenderly.co/api/v1/account/${process.env.REACT_APP_TENDERLY_USER}/project/${process.env.REACT_APP_TENDERLY_PROJECT}/simulate`,
we should show this to the user imo

2023-02-08 11:16 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +        `https://api.tenderly.co/api/v1/account/${process.env.REACT_APP_TENDERLY_USER}/project/${process.env.REACT_APP_TENDERLY_PROJECT}/simulate`,
That was the impression I got. Here I am just referencing the fact that this will expose API keys so we need to route the call via a server.

2023-02-08 11:38 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +            optionExchangeContract?.operate(txData, { gasLimit: 2500000 });
simulation is just to make sure smart contract call with actually go through and not end up wasting users funds (attached as gas)

2023-02-08 11:41 UTC, devey commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +        `https://api.tenderly.co/api/v1/account/${process.env.REACT_APP_TENDERLY_USER}/project/${process.env.REACT_APP_TENDERLY_PROJECT}/simulate`,
gnosis is a bit different as users there usually decided that they want to interact with a certain contract, import it's ABIs and then gnosis helps them by putting together a simulation that they can look into; here it would be a bonus. can do it later to add a link to the simulation (need to double that would actually be public)

2023-02-10 12:12 UTC, MeanBoyCousin requested changes
Looking good, just a few things.

2023-02-10 12:12 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +      setLoading(false);
Be good to chuck a captureException for Sentry in here.

2023-02-15 15:07 UTC, devey commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +const TENDERLY_ACCESS_KEY = process.env.REACT_APP_TENDERLY_ACCESS_KEY;
yeah the only ways to fix this is to run an AWS Lambda, which I can set up when things are calmer :)

2023-02-15 15:56 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  simulateError && toast(simulateError as string);
yeah this one is if there is any error in the `fetch` while the one above is if the actual simulation is failing. gonna have to Clean it up this anyway soon

2023-02-15 16:45 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useTenderlySimulator/index.tsx
> +const TENDERLY_ACCESS_KEY = process.env.REACT_APP_TENDERLY_ACCESS_KEY;
I think the easier option is just to use a server route in NextJS once we move over. I guess that'll have to be an accepted risk for now. I will make a note in the sec channel so everyone is aware.

2023-02-15 16:53 UTC, MeanBoyCousin approved these changes
Looks good, have noted the security risk for future mitigation.

2023-02-15 17:41 UTC, merged