Approve exchange as operator
rysk-finance/dynamic-hedging pull request #395
Opened 2023-02-08 16:51 UTC by devey

Add a hook for reading from `Controller` if exchange is operator of address and hook up method for setting it.

2023-02-15 17:38 UTC, MeanBoyCousin requested changes
Code wise all looking good. Just a few things on typing to help improve clarity. Let me know if you need a hand with the shell script bits. 👍

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  const [, setCollateral] = useState("");
Does this need to be set if it isn't being read?

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/types/global.d.ts
> +declare module "implied-volatility";
Looks like this has snuck in here. Might be something to do with how you're rebasing. Can hop on a call and take a look at some point 👍 For now you should be able to drop the commit with an interactive rebase.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +
Why are the above being reassigned?

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +import MarginCollateralABI from "../../abis/opyn/NewMarginCalculator.json";
If you look in the ABIs folder, you will see that I have generated TypeScript versions of the JSON files. This is because the type inference with the Wagmi stuff doesn't work from JSON. You'll see in the others that it exports the ABI which is typecast `as const` which provides much better type inference. In the case of this hook, it'll tell you for instance that a lot of the variables typed as strings should in fact be BigNumbers.

Side note on this, can you update the shell script for copying these new ABIs over so that it gets done automatically, please?

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/CollateralRequirement/index.tsx
> +  const underlying = addresses[network].WETH;
Should be able to use the `getContractAddress` helper here.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useApproveExchange/index.tsx
> +import OpynControllerABI from "../../abis/OpynController.json";
See other comment on TS ABI vs JSON.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useApproveTransfer/index.tsx
> +import ERC20ABI from "../../abis/erc20.json";
See other comment on TS ABI vs JSON.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useApproveTransfer/index.tsx
> +      setAllowance(current as BigNumber);
Might be able to avoid the typecast with better inference from the Typescript ABI.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useApproveTransfer/index.tsx
> +    readAllowance().catch(console.log);
If we're keeping this catch, a Sentry call would be good. 👍 

tbh there is a Sentry capture console plugin of sorts that we should just use instead for all logs of error and above.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useOraclePrice/index.tsx
> +import OpynOracleABI from "../../abis/opyn/Oracle.json";
See other comment on TS ABI vs JSON.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useSellOperate/index.tsx
> +import OptionExchangeABI from "../../abis/OptionExchange.json";
See other comment on TS ABI vs JSON.

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useSellOperate/index.tsx
> +  const underlying = wethAddress;
Do these need to be re-assigned?

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useSellOperate/index.tsx
> +      gasLimit: BigNumber.from("2500000"),
Worth bumping this to 3,000,000 as per the issues we saw earlier today?

2023-02-15 17:38 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/CollateralRequirement/index.tsx
> +      setMargin(marginRequirement as string);
Might be able to avoid the typecast with better type inference in the hook. See other comments. 👍

2023-02-22 10:34 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  const [, setCollateral] = useState("");
yep, can be removed

2023-02-22 10:35 UTC, devey commented on packages/front-end/src/types/global.d.ts
> +declare module "implied-volatility";
looks good now

2023-02-22 10:36 UTC, devey commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +
just trying to make it explicit as we'll probably update these hooks to support different combinations of strike, underlying and collateral (mostly collateral for now as it could be `USDC` or `ETH`)

2023-02-22 10:41 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +
Ok makes sense. It's still additional memory but I guess it's O(1) so not a biggie.

2023-02-22 11:12 UTC, devey commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +import MarginCollateralABI from "../../abis/opyn/NewMarginCalculator.json";
thanks, I added files to export `ts` for the two ABIs I added (Opyn Oracle and Margin Calculator).
The reason I didn't add them to be copied int the script is cause one of these files is 10k lines and the other 40k and we literally just need 20 of those :)

2023-02-22 12:01 UTC, devey commented on packages/front-end/src/hooks/useSellOperate/index.tsx
> +  const underlying = wethAddress;
same as above, just to make explicit in the hook the structure of the options

2023-02-22 12:04 UTC, MeanBoyCousin commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +import MarginCollateralABI from "../../abis/opyn/NewMarginCalculator.json";
Ahh right ok. The `jq` tool we're using to extract the data can grab nested sections of JSON so maybe we can customize the script for those. They'll have to be in the script somehow though as the script itself does an `rm -rf` on the ABIs folder so anything added manually will get wiped next time we run a compile.

2023-02-22 13:08 UTC, devey commented on packages/front-end/src/hooks/useApproveTransfer/index.tsx
> +    readAllowance().catch(console.log);
I actually had an oversight here, should have just used `useContractRead`, will refactor this hook while updating these hooks to support different collaterals (already did for one of them to try it out)

2023-02-22 13:10 UTC, devey commented on packages/front-end/src/hooks/useApproveTransfer/index.tsx
> +    readAllowance().catch(console.log);
for now I just added the sentry `captureException` in the catch

2023-02-22 13:46 UTC, devey commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +import MarginCollateralABI from "../../abis/opyn/NewMarginCalculator.json";
cleaned up this hook with `useContractRead` ;)

2023-02-23 10:26 UTC, devey commented on packages/front-end/src/hooks/useMarginRequirement/index.tsx
> +import MarginCollateralABI from "../../abis/opyn/NewMarginCalculator.json";
Created an issue for this: #424

2023-02-23 12:49 UTC, merged