Option chain UI improvements
rysk-finance/dynamic-hedging pull request #413
Opened 2023-02-16 14:00 UTC by MeanBoyCousin

# Task: General improvements to the option chain UI.

## Description

- Updates to a newer version of the Ethereum logo.
- Small bug fixes.
- Visualise the user's open positions for each expiry and strike. (Currently only working for longs pending graph updates and short work)
- Better colorisation of the option chain.
- General refactoring.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document update
- [ ] Quality of life improvement
- [ ] Package upgrades

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have NATSPEC'd any new functions
- [ ] If appropriate, I have properly tested my new functionality

2023-02-23 10:44 UTC, devey commented on packages/front-end/src/components/optionsTrading/ExpiryDatePicker/hooks/useExpiryDates.tsx
> +            .reduce((expiryDates: ExpiryDateList, expiration: BigNumber) => {
there is the query on The Graph now for fetching this, it's not definitive interface but better start using it now so we figure out if it needs changes

2023-02-23 11:04 UTC, devey approved these changes
utACK

Code looks good but wasn't able to user test as tx to buy seem to be failing with an intrinsic gas too low error (got the same on my pr so not sure if it has to do with my local setup, looking into it).

2023-02-23 11:44 UTC, devey requested changes

2023-02-23 11:44 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +          collateral: getContractAddress("optionExchange"),
This should be `USDC`

2023-02-23 11:51 UTC, devey commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +                    value={option.put.pos}
this will have to change in case user also sold this position, so this once we merge shorting i guess @ugolino how is this usually done just netting out of bid and ask positions (askPos - bidPos) ?

2023-02-24 16:01 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +                    decimalScale={2}
Makes sense, will tweak.

2023-02-24 16:01 UTC, devey commented on packages/front-end/src/components/optionsTrading/ExpiryDatePicker/hooks/useExpiryDates.tsx
> +            .reduce((expiryDates: ExpiryDateList, expiration: BigNumber) => {
sounds good

2023-02-24 16:02 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +          collateral: getContractAddress("optionExchange"),
Good spot!

2023-02-24 16:03 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/OptionsTable.tsx
> +                    value={option.put.pos}
Yeah, I figured it'd need to change, especially as I am only querying for long positions right now. Something we should look at tweaking once the graph work is done. In the mean time I will try to tidy this massive file into components so we can make easy changes going forward.

2023-02-27 11:18 UTC, devey approved these changes
great

2023-02-27 11:24 UTC, merged