Update price and fees based on order size
rysk-finance/dynamic-hedging pull request #438
Opened 2023-03-08 12:04 UTC by devey

Create a hook to take care of retrieving option premium and fees based on changes of order size.

2023-03-08 12:49 UTC, MeanBoyCousin requested changes
Just a few bits of house-keeping. 👍

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +    args: [oHash || ZERO_ADDRESS],
Why the `||`? If it has to be truthy to be enabled then it shouldn't need a fallback.

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +        strike: toWei(selectedOption?.strikeOptions.strike.toString() || "0"),
Same as the comment above on the `||`.

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +      toWei(orderSize?.toString() || "0"), // 1 for the table view but fetch if user wants to buy more
and here.

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +      exposure || BigNumber.from(0),
and here.

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +    ) as HexString);
Seeing as we're doing this in a couple of places now, can you turn it into a util function please and then implement its usage where needed?

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
What happens if either of these is false?

2023-03-08 12:49 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +  console.log("Premium and Fees: ", premium, fees);
Remove, please.

2023-03-08 13:36 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
they either are `BigNumber` objects or they are `undefined`,  no?

2023-03-08 13:41 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
Sorry, I mean in terms of the UI. What will the user see?

2023-03-08 13:55 UTC, devey commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +    ) as HexString);
done

2023-03-10 10:22 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
nothing, it just shows up after use inputs an option amount

2023-03-10 11:15 UTC, devey commented on packages/front-end/src/components/optionsTrading/hooks/useQuoteOptionPrice.tsx
> +    args: [oHash || ZERO_ADDRESS],
It seems like `useContractRead` doesn't actually operate like that internally

2023-03-10 11:15 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
Sorry, my point is that if they input an amount and then there is say an error or a bad value for one of these, what happens then? My understanding here is there is no error state UI or notification. Just thought it could be confusing if the user inputs an amount and then nothing happens.

2023-03-13 11:50 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +                    {premium && fees && (
oh, got it. I added a toast for error and a message on loading

2023-03-13 12:19 UTC, MeanBoyCousin approved these changes
Just one thing, not necessarily a big deal right now but something to think about.

2023-03-13 12:19 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +    toast(quoteError.message, { type: "error" });
Does this expose the generic error from Wagmi? Something more user-friendly would probably be better. I'd like to standardise the tone a bit more ideally as we have quite sporadic messaging and often these generic messages from providers or RPC are completely unhelpful.

2023-03-14 10:04 UTC, devey commented on packages/front-end/src/components/optionsTrading/Purchase.tsx
> +    toast(quoteError.message, { type: "error" });
yeah we need to find an approach to user messaging and be consistent with it, agreed. I don't like having a global error component where everything is shown but would be up with components UI reacting to errors properly. Components based vs Global I'd say. we can discuss this as a refactor, at least for the most error, info prone components.

2023-03-28 10:11 UTC, MeanBoyCousin approved these changes

2023-03-28 10:12 UTC, closed without merging