Complete Dashboard actions
rysk-finance/dynamic-hedging pull request #448
Opened 2023-03-20 12:10 UTC by devey

2023-04-18 11:18 UTC, MeanBoyCousin requested changes

2023-04-18 11:18 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Modals/CloseOptionModal/index.tsx
> +  const [searchParams] = useSearchParams();
It doesn't look like any of the changes in here are being used?

2023-04-18 11:18 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Modals/CloseShortOptionModal/hooks/useShortPositionData.tsx
> +
I'd like all of the graph queries to be hoisted into the `useInitialData` hook and stored in global state to save on network load, please. You should find that some of this is already being stored which you can argument with your changes and then run queries against global state for the `vaultId` that you need.

I think this same query exists in the dashboard code as well so also a good chance to dedupe.

2023-04-18 11:18 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/Modals/Shared/utils/transactions.ts
> +          indexOrAcceptablePremium: BigNumber.from(0),
This (and any other `indexOrAcceptablePremium` inside a RyskAction will now need to be updated to be the value of the total premium for the transaction. For now, Jib has stated that `for selling the indexOrAcceptablePremium should be quote * 97% and for buying should be quote * 103%`.

You can see this PR for some examples: https://github.com/rysk-finance/dynamic-hedging/pull/470/

2023-04-18 11:18 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useModal.tsx
> +import { BigNumber } from "ethers";
Import sorting please.

2023-04-18 11:18 UTC, MeanBoyCousin commented on packages/front-end/src/components/optionsTrading/hooks/useModal.tsx
> +      });
Just to clarify here, is the user being sent to the options chain page and then this modal opens? Just wondering why dashboard related modals are being triggered outside of the dashboard.

2023-04-19 00:25 UTC, devey commented on packages/front-end/src/components/optionsTrading/hooks/useModal.tsx
> +      });
mostly to avoid too much copy pasted code but I can move it out

2023-04-19 00:29 UTC, devey commented
- [ ] change ui of Close Button

2023-04-19 02:03 UTC, devey commented on packages/front-end/src/components/optionsTrading/Modals/CloseShortOptionModal/hooks/useShortPositionData.tsx
> +
makes sense, thanks. I moved it under the initial query (not under vault cause it's easier to just get it under the actual position)

2023-04-19 10:27 UTC, ugolino commented on packages/front-end/src/components/dashboard/OptionsTable/components/Table.tsx
> +              decimalScale={2}
this doesnt seem to work. decimal seems to be always 1

![Uploading Screenshot 2023-04-19 at 19.27.15.png…]()

2023-04-19 10:29 UTC, ugolino commented on packages/front-end/src/components/dashboard/OptionsTable/components/Table.tsx
> +                      onClick={adjustCollateral}
this should be available only if option is not expired. don't think it makes sense to let user adjust collateral after expiration since it can just settle

2023-04-19 10:54 UTC, ugolino commented
Few comments:
- might make sense to split the table between active (not expired) and expired ones. Will make table more readable since most of the fields are unique to expired or active positions. on the sorting we can have `asc` for active, and `desc` for expired - since will make sense to see the most recent expiries first to perform settle redeem 
- add liquidation price after the p.r with liquidation is merged in
- on the collateral management might be worth add the liquidation price as well with before adding/remove and after so it is easy to see the impact
- add the current price to close position (if position is short will be the price to buy, and the other way around)
- based on the current price we can have a PnL field as well

2023-05-01 06:47 UTC, ugolino commented on packages/front-end/src/components/dashboard/OptionsTable/OptionsTable.tsx
> +            loading && !inactivePositions ? "Loading Closed..." : "RYSK.Closed",
```suggestion
            loading && !inactivePositions ? "Loading Closed..." : "RYSK.Expired",
```

2023-05-02 08:25 UTC, ugolino approved these changes

2023-05-02 09:02 UTC, closed without merging